fos_rest:
    disable_csrf_role: ROLE_API
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
        templating_formats:
            html: true
    format_listener:
        rules:
            - { path: ^/api, priorities: [json, xml, html], fallback_format: json, prefer_extension: false }
            - { path: ^/, prefer_extension: false, priorities: [html, xml, json] }
            # - { path: ^/, priorities: [  json, xml, html], fallback_format: json, prefer_extension: true }
            # - { path: ^/api/foo, priorities: [ json, html,  xml ], fallback_format: ~, prefer_extension: false }
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: false
    access_denied_listener:
        json: true
    body_listener:
        decoders: 
            json: fos_rest.decoder.json
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors