security:
    encoders:
        FOS\UserBundle\Model\UserInterface : sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    restapi:  { password: secretpw, roles: [ 'ROLE_API' ] }
        basic:
            memory:
                users:
                    admin:
                        password: admin
                        roles: [ROLE_SUPER_ADMIN]
    firewalls:
        dev:
            pattern: ^ / (_ (profiler | wdt) | css | images | js) /
            security: false
            # anonymous: ~
        main:
            pattern: ^/
            form_login: 
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                use_forward: false
                always_use_default_target_path: true
                username_parameter: _username
                password_parameter: _password
                post_only:      true
                remember_me:    false
            logout:       true
            anonymous:    true
            # http_basic:
            #     realm: "Demo REST API (username: restapi, password: secretpw)"

    # controll access here!
    # - arek
    access_control:
        - { path: ^/api/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        # - { path: ^/api/, roles: ROLE_USER } #, requires_channel: https
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }