# services:
#   isAuthorized:
#     class: Symfonier\ApiBundle\EventListener\RequestListener
#     arguments: ["@security.context"]
#     tags:
#         - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
